### ISSUE TITLE
Better training.py enhancement

### ISSUE THREAD

**Issue by changcheng967** [Doulet-Media/Kata_speed#25]
add more!

**Comment by DouletMedia** [comment]
you do it

**Comment by changcheng967** [comment]
fine

**Comment by DouletMedia** [comment]
@changcheng967 good

**Comment by changcheng967** [comment]
> @changcheng967 good

yep

**Comment by changcheng22023** [comment]
hi

**Comment by changcheng967** [comment]
> hi

hi

**Comment by changcheng967** [comment]
@changchengdouletmedia 
https://github.com/changcheng967/Kata_speed/pull/41
Why do you revert this?

**Comment by changcheng967** [comment]
This is expecially not allowed in our repositories

**Comment by changcheng967** [comment]
and DouletMedia too @DouletMedia

**Comment by changchengdouletmedia** [comment]
> @changchengdouletmedia #41 Why do you revert this?

I just want to let my name on that
