### ISSUE TITLE
train.py file missing

### ISSUE THREAD

**Issue by DouletMedia** [Doulet-Media/Kata_speed#27]
### Discussed in https://github.com/changcheng967/Kata_speed/discussions/26

<div type='discussions-op-text'>

<sup>Originally posted by **changcheng967** June 19, 2024</sup>
should we change it to bin.gz because that's easier</div>

**Comment by changcheng6541** [comment]
this doesn't sounds great

**Comment by changcheng967** [comment]
yep

**Comment by changcheng967** [comment]
pretty bad
