### ISSUE TITLE
Issue submitted by <changchengdouletmedia@gmail.com>

### ISSUE THREAD

**Issue by changcheng967** [Doulet-Media/Kata_speed#52]
<html>
<body>
<div class="gE iv gt" style="font-size: 0.875rem; cursor: auto; padding: 20px 0px 0px; color: rgb(34, 34, 34); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
Chang Chang <changchengdouletmedia@gmail.com> | Chang Chang <changchengdouletmedia@gmail.com> | 6:21 PM (57 minutes ago) |   |  
-- | -- | -- | -- | --
Chang Chang <changchengdouletmedia@gmail.com>
to me | to me
to me

</div><div id=":mm" style="color: rgb(34, 34, 34); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="qQVYZb"></div><div class="utdU2e"></div><div class="lQs8Hd" jsaction="SN3rtf:rcuQ6b" jscontroller="i3Ohde"></div><div class="wl4W9b" jsaction="LNSvUb:.CLIENT;xSdBYb:.CLIENT;CDWmBe:.CLIENT;EtHLdc:.CLIENT;pQnh7:.CLIENT;pKHw7e:.CLIENT;Z03mxd:.CLIENT;NZLNxf:.CLIENT;bXglpe:.CLIENT;mzh2Bc:.CLIENT" style="display: flex;"></div></div><div class="" style="color: rgb(34, 34, 34); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="aHl" style="margin-left: -38px;"></div><div id=":n3" tabindex="-1"></div><div id=":nd" class="ii gt" jslog="20277; u014N:xr6bB; 1:WyIjdGhyZWFkLWY6MTgwMzE0NTIzMjEzNzA3MDg2NiJd; 4:WyIjbXNnLWY6MTgwMzE0NTIzMjEzNzA3MDg2NiJd" style="direction: ltr; margin: 8px 0px 0px; padding: 0px; position: relative; font-size: 0.875rem; overflow-x: hidden;"><div id=":ml" class="a3s aiL " style="direction: initial; font: small / 1.5 Arial, Helvetica, sans-serif; overflow: auto hidden; position: relative;"><div dir="ltr">Emergency report, @changchengdouletmedia just uploaded a file called crasher.bat<br><br><a href="https://github.com/changcheng967/Kata_speed/commit/c3917fc843f9ec6395be01fe5508b92a584ebc1d" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://github.com/changcheng967/Kata_speed/commit/c3917fc843f9ec6395be01fe5508b92a584ebc1d&amp;source=gmail&amp;ust=1719703019674000&amp;usg=AOvVaw0uakHDmaJK-4NLP7TgMpbu" style="color: rgb(17, 85, 204);">https://github.com/<wbr>changcheng967/Kata_speed/<wbr>commit/<wbr>c3917fc843f9ec6395be01fe5508b9<wbr>2a584ebc1d</a></div></div></div></div>
</body>
</html>

**Comment by changcheng967** [comment]
email original file

https://github.com/changcheng967/Kata_speed/blob/new-bot/Security%20report.eml

**Comment by changchengdouletmedia** [comment]
```html
MIME-Version: 1.0
Date: Fri, 28 Jun 2024 18:21:22 -0400
Message-ID: <CAHe=zURbwYfvEJ+KurHjXay6n6j_gARNySLBgRgqDMKPUh9wFg@mail.gmail.com>
Subject: Security report
From: Chang Chang <changchengdouletmedia@gmail.com>
To: "changcheng6541@gmail.com" <changcheng6541@gmail.com>
Content-Type: multipart/alternative; boundary="000000000000eddf9a061bfaaab7"

--000000000000eddf9a061bfaaab7
Content-Type: text/plain; charset="UTF-8"

Emergency report, @changchengdouletmedia just uploaded a file called
crasher.bat

https://github.com/changcheng967/Kata_speed/commit/c3917fc843f9ec6395be01fe5508b92a584ebc1d

--000000000000eddf9a061bfaaab7
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr">Emergency report,=C2=A0@changchengdouletmedia just uploade=
d a file called crasher.bat<br><br><a href=3D"https://github.com/changcheng=
967/Kata_speed/commit/c3917fc843f9ec6395be01fe5508b92a584ebc1d">https://git=
hub.com/changcheng967/Kata_speed/commit/c3917fc843f9ec6395be01fe5508b92a584=
ebc1d</a><br></div>

--000000000000eddf9a061bfaaab7--
```

**Comment by changchengdouletmedia** [comment]
> email original file
> 
> https://github.com/changcheng967/Kata_speed/blob/new-bot/Security%20report.eml

MIME-Version: 1.0 Date: Fri, 28 Jun 2024 18:21:22 -0400 Message-ID: Subject: Security report From: Chang Chang To: "changcheng6541@gmail.com" Content-Type: multipart/alternative; boundary="000000000000eddf9a061bfaaab7" --000000000000eddf9a061bfaaab7 Content-Type: text/plain; charset="UTF-8" Emergency report, @changchengdouletmedia just uploaded a file called crasher.bat https://github.com/changcheng967/Kata_speed/commit/c3917fc843f9ec6395be01fe5508b92a584ebc1d --000000000000eddf9a061bfaaab7 Content-Type: text/html; charset="UTF-8" Content-Transfer-Encoding: quoted-printable
Emergency report,=C2=A0@changchengdouletmedia just uploade= d a file called crasher.bat

[https://git= hub.com/changcheng967/Kata_speed/commit/c3917fc843f9ec6395be01fe5508b92a584= ebc1d](https://www.w3schools.com/html/3D%22https://github.com/changcheng=)
--000000000000eddf9a061bfaaab7--

**Comment by changchengdouletmedia** [comment]
Me? Not possiable

**Comment by changcheng22023** [comment]
yeah how come he will submit3 a virus

**Comment by changcheng967** [comment]
> yeah how come he will submit3 a virus

That's what I'm wondering

**Comment by changcheng967** [comment]
> > yeah how come he will submit3 a virus
> 
> That's what I'm wondering

Not possiable

**Comment by changcheng967** [comment]
Is is some random person just want to make us in to a serious issue

**Comment by changcheng967** [comment]
we need to strong our security code check

**Comment by changcheng22023** [comment]
Agree

**Comment by changcheng22023** [comment]
<details><summary>Details</summary>
<p>

MIME-Version: 1.0 Date: Fri, 28 Jun 2024 18:21:22 -0400 Message-ID: Subject: Security report From: Chang Chang To: "changcheng6541@gmail.com" Content-Type: multipart/alternative; boundary="000000000000eddf9a061bfaaab7" --000000000000eddf9a061bfaaab7 Content-Type: text/plain; charset="UTF-8" Emergency report, @changchengdouletmedia just uploaded a file called crasher.bat https://github.com/changcheng967/Kata_speed/commit/c3917fc843f9ec6395be01fe5508b92a584ebc1d --000000000000eddf9a061bfaaab7 Content-Type: text/html; charset="UTF-8" Content-Transfer-Encoding: quoted-printable
Emergency report,=C2=A0@changchengdouletmedia just uploade= d a file called crasher.bat

[https://git= hub.com/changcheng967/Kata_speed/commit/c3917fc843f9ec6395be01fe5508b92a584= ebc1d](https://www.w3schools.com/html/3D%22https://github.com/changcheng=)
--000000000000eddf9a061bfaaab7--

</p>
</details>

**Comment by changcheng22023** [comment]
#51 it has already being tyere since that pull request

**Comment by changcheng22023** [comment]
no one reviewed it

**Comment by changcheng22023** [comment]
Shit

**Comment by changcheng967** [comment]
yeah

**Comment by changcheng967** [comment]
@changchengdouletmedia did someone hack into your account

**Comment by changchengdouletmedia** [comment]
no

**Comment by changchengdouletmedia** [comment]
but why

**Comment by changcheng967** [comment]
Already deleted Thank you
