### ISSUE TITLE
Bot can not place stone on the board

### ISSUE THREAD

**Issue by changchengdouletmedia** [Doulet-Media/Kata_speed#53]
The executable file is generated by cmake but the bot can not place any stone

**Comment by changcheng967** [comment]
We plan to use KataGo's network and config file

**Comment by changcheng967** [comment]
which should work at least

**Comment by changchengdouletmedia** [comment]
ok

**Comment by changcheng967** [comment]
[新建 文本文档 (2).txt](https://github.com/user-attachments/files/16075822/2.txt)

**Comment by changcheng967** [comment]
error code

**Comment by changchengdouletmedia** [comment]
We need to ask the KataGo professional to solve this

**Comment by changcheng967** [comment]
> We need to ask the KataGo professional to solve this

yeah

**Comment by changcheng967** [comment]
Duplicate of #60

**Comment by changcheng967** [comment]
this make does not how anything, vs code does not show anything either

**Comment by changchengdouletmedia** [comment]
that's weird

**Comment by changchengdouletmedia** [comment]
is it the problem with cmake

**Comment by changchengdouletmedia** [comment]
MZ� Did you generate the file again

https://github.com/changcheng967/Kata_speed/blob/new-bot/build/KataSpeed.exe

**Comment by changcheng967** [comment]
yeah if I am right

**Comment by changcheng967** [comment]
the #60 shows it

**Comment by changcheng967** [comment]
the #61 is aparently not working

**Comment by changchengdouletmedia** [comment]
then we should take it down

**Comment by changchengdouletmedia** [comment]
I deleted those two

**Comment by changcheng967** [comment]
good

**Comment by changchengdouletmedia** [comment]
the problem is still not fixed @changcheng967

**Comment by changcheng967** [comment]
yeah and I have no idea why

**Comment by changcheng967** [comment]
I already submit the open-source request to let people test this

**Comment by changchengdouletmedia** [comment]
> I already submit the open-source request to let people test this

good

**Comment by changchengdouletmedia** [comment]
we should've submit a new release for people test

**Comment by changcheng967** [comment]
ok

**Comment by DouletMedia** [comment]
I don't think mergify is working

**Comment by DouletMedia** [comment]
aparrently

**Comment by changcheng967** [comment]
that is pretty correct

> aparrently

**Comment by changcheng967** [comment]
#78 #79

**Comment by changcheng967** [comment]
#80 #81

**Comment by changcheng967** [comment]
Bye guys

**Comment by changcheng6541** [comment]
Hihihi

**Comment by changcheng6541** [comment]
added yike linker

**Comment by changcheng6541** [comment]
any one know how ton use that

**Comment by changcheng6541** [comment]
sign

**Comment by changcheng6541** [comment]
#87 #86 #85 #84 #83 #82

**Comment by changcheng967** [comment]
OK we are back

**Comment by changcheng967** [comment]
but your will still be put away since I considered with [xqqzldh](https://online-go.com/player/1241203/) because we are archiving our engine and using katago engine but using our self trained b30 network

**Comment by changcheng967** [comment]
We are using KataGo engine and training our b20 network so this should be solved
