### ISSUE TITLE
Accordingly, I think the b60 netwokr is not used to train

### ISSUE THREAD

**Issue by changcheng967** [Doulet-Media/Kata_speed#96]
Accordingly, I think the b60 netwokr is not used to train

_Originally posted by @DouletMedia in https://github.com/changcheng967/Kata_speed/issues/95#issuecomment-2256549621_

**Comment by changcheng967** [comment]
other network is not showing up

**Comment by changcheng967** [comment]
according to #95

**Comment by changcheng967** [comment]
https://github.com/changcheng967/Kata_speed/pull/95#pullrequestreview-2205614913

**Comment by DouletMedia** [comment]
> [#95 (review)](https://github.com/changcheng967/Kata_speed/pull/95#pullrequestreview-2205614913)

Requested you to change

**Comment by DouletMedia** [comment]
after this one training, we should pull this request and follow KataGo to 1.15.0 and 1.15.1

**Comment by changcheng967** [comment]
May be fixed by training next time
